version: "3.9"

services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=demo-service-connection
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - postgres-storage:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-storage:/var/lib/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
  zipkin:
    image: 'openzipkin/zipkin:latest'
    container_name: zipkin
    restart: unless-stopped
    ports:
      - '9411:9411'

volumes:
  postgres-storage:
  grafana-storage:
  prometheus-storage:

