spring:
  application:
    name: demo-service-connection
  datasource:
    url: "jdbc:postgresql://localhost:5432/demo-service-connection"
    username: "spring"
    password: "secret"
  sql:
    init:
      mode: always

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics